### ISSUE TITLE
data processing for nuscene

### ISSUE THREAD

**Issue by Jieqianyu** [ucaszyp/MonoOcc#1]
Thank you for sharing your excellent work! I am confused about the pseudo LiDAR for nuscene. How can I obtain the voxelized pseudo Lidar "nuscenes-voxel-midas-sweep0“? Could you please provide more details about that? Thanks again!

**Comment by ucaszyp** [comment]
We use MiDas/Metric 3D to estimate depth to generate pesudo LiDAR. You can also use Depth Anything to generate pseudo LiDAR. It is worth noting that when generating the pseudo point cloud, we only considered the lower part (2/3) of the image. Additionally, we applied a 1/16 downsampling to the generated pseudo point cloud.

**Comment by Jieqianyu** [comment]
Thank you for your reply!
